/**
 * nff.h — nff device SDK public API
 *
 * Single include for device firmware. Pair with credentials.h (generated by
 * `nff provision new-device --id <id>`) which provides the DER-encoded
 * certificate/key byte arrays consumed by NFF_CONFIG / NFF_CONFIG_INITIALIZER.
 *
 * Minimal Arduino usage:
 *
 *   #include <nff.h>
 *   #include "credentials.h"
 *
 *   NFF_CONFIG(cfg, "device-42", "nff.yourdomain.com");
 *
 *   void setup() {
 *       // ... WiFi.begin() / WiFi.waitForConnectResult() ...
 *       nff_init(&cfg);
 *       nff_connect();
 *   }
 *   void loop() {
 *       nff_loop();
 *       // your code
 *   }
 *
 * Command signature format (TBS = to-be-signed):
 *   ping/reboot/diag: "{action}|{nonce}|{timestamp_decimal}"
 *   ota:              "ota|{version}|{sha256hex}|{nonce}|{timestamp_decimal}"
 *   custom:           "{action}|{nonce}|{timestamp_decimal}"
 *   ECDSA-P256 signs SHA-256(TBS). nff server holds the matching private key.
 */

#ifndef NFF_H
#define NFF_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* ------------------------------------------------------------------ */
/* Error codes                                                          */
/* ------------------------------------------------------------------ */
#define NFF_OK                  0
#define NFF_ERR_UNINIT         (-1)
#define NFF_ERR_INVALID_ARG    (-2)
#define NFF_ERR_NO_MEM         (-3)
#define NFF_ERR_MQTT           (-4)
#define NFF_ERR_OTA            (-5)
#define NFF_ERR_SECURITY       (-6)
#define NFF_ERR_NOT_SUPPORTED  (-7)
#define NFF_ERR_TIMEOUT        (-8)
#define NFF_ERR_DOWNGRADE      (-9)
#define NFF_ERR_CHECKSUM       (-10)

/* ------------------------------------------------------------------ */
/* SDK state                                                            */
/* ------------------------------------------------------------------ */
typedef enum {
    NFF_STATE_UNINIT     = 0,
    NFF_STATE_CONNECTING,
    NFF_STATE_CONNECTED,
    NFF_STATE_OTA_ACTIVE,
    NFF_STATE_ERROR
} nff_state_t;

/* ------------------------------------------------------------------ */
/* Configuration                                                        */
/* ------------------------------------------------------------------ */
typedef struct {
    const char    *device_id;
    const char    *broker_host;
    uint16_t       broker_port;        /* default: 8883 (TLS) */

    /* mTLS — DER-encoded byte arrays from credentials.h */
    const uint8_t *client_cert;        size_t client_cert_len;
    const uint8_t *client_key;         size_t client_key_len;
    const uint8_t *ca_cert;            size_t ca_cert_len;

    /* Fleet command verify key: 65-byte uncompressed P-256 point (0x04 || X || Y) */
    const uint8_t *cmd_verify_key;     size_t cmd_verify_key_len;

    /* Firmware identity — injected by build system via -DNFF_FW_VERSION=... */
    const char    *fw_version;
    const char    *build_id;           /* 16-char hex prefix of ELF SHA-256 */

    /* Tuning */
    uint32_t       heartbeat_interval_s;  /* 0 = use default (30) */
} nff_config_t;

/* ------------------------------------------------------------------ */
/* Config convenience macros (require credentials.h in scope)          */
/* ------------------------------------------------------------------ */

/* Arduino / C++ global initializer — positional, C++ compatible */
#define NFF_CONFIG(var, id, host)                               \
    nff_config_t var = {                                        \
        (id),                                                   \
        (host),                                                 \
        8883,                                                   \
        NFF_CLIENT_CERT_DER,  NFF_CLIENT_CERT_LEN,             \
        NFF_CLIENT_KEY_DER,   NFF_CLIENT_KEY_LEN,              \
        NFF_CA_CERT_DER,      NFF_CA_CERT_LEN,                 \
        NFF_CMD_VERIFY_KEY_DER, NFF_CMD_VERIFY_KEY_LEN,        \
        NFF_FW_VERSION,                                         \
        NFF_BUILD_ID,                                           \
        30                                                      \
    }

/* ESP-IDF / C99 designated initializer */
#define NFF_CONFIG_INITIALIZER(id, host) {                      \
    .device_id            = (id),                               \
    .broker_host          = (host),                             \
    .broker_port          = 8883,                               \
    .client_cert          = NFF_CLIENT_CERT_DER,                \
    .client_cert_len      = NFF_CLIENT_CERT_LEN,                \
    .client_key           = NFF_CLIENT_KEY_DER,                 \
    .client_key_len       = NFF_CLIENT_KEY_LEN,                 \
    .ca_cert              = NFF_CA_CERT_DER,                    \
    .ca_cert_len          = NFF_CA_CERT_LEN,                    \
    .cmd_verify_key       = NFF_CMD_VERIFY_KEY_DER,             \
    .cmd_verify_key_len   = NFF_CMD_VERIFY_KEY_LEN,             \
    .fw_version           = NFF_FW_VERSION,                     \
    .build_id             = NFF_BUILD_ID,                       \
    .heartbeat_interval_s = 30,                                 \
}

/* Zephyr: compile-time thread definition (V1: real port deferred — stub only) */
#define NFF_THREAD_DEFINE(var, id, host)  \
    nff_config_t var = NFF_CONFIG_INITIALIZER((id), (host))

/* ------------------------------------------------------------------ */
/* Command handler                                                      */
/* ------------------------------------------------------------------ */

/**
 * Handler for user-registered commands. Called on the nff task/loop when
 * a signed command arrives. Write JSON to response_buf (null-terminated);
 * the SDK publishes it to nff/devices/{id}/response.
 *
 * payload      — null-terminated JSON string of the full command
 * response_buf — write your JSON reply here; max response_len bytes
 * user_ctx     — opaque pointer passed to nff_register_command
 */
typedef void (*nff_cmd_handler_t)(const char  *payload,
                                   char        *response_buf,
                                   size_t       response_len,
                                   void        *user_ctx);

/* ------------------------------------------------------------------ */
/* Public API                                                           */
/* ------------------------------------------------------------------ */

/**
 * nff_init — initialise the SDK.
 *
 * Call once before WiFi connect. Installs the panic hook, detects a
 * crash on the previous boot, and checks for a pending OTA result.
 * Safe to call from app_main (ESP-IDF) or global constructors (Arduino).
 */
int nff_init(const nff_config_t *cfg);

/**
 * nff_connect — connect to the nff broker.
 *
 * Call after WiFi is up. Performs the mTLS handshake, publishes the
 * retained heartbeat, and subscribes to the command topic.
 * Returns NFF_OK on success. On failure the SDK will retry automatically
 * via nff_loop() / the internal FreeRTOS task.
 */
int nff_connect(void);

/**
 * nff_loop — non-blocking poll for Arduino sketch loop().
 *
 * Drives MQTT keepalive, reconnect backoff, and heartbeat timer.
 * Returns in < 1 ms when there is no pending work.
 */
void nff_loop(void);

/**
 * nff_start_task — create a FreeRTOS task for nff (ESP-IDF / Arduino-FreeRTOS).
 *
 * Pins the task to Core 0, runs at priority 2 (lower than any application task).
 * Returns immediately. The application continues on Core 1.
 * Do NOT call nff_loop() when using nff_start_task().
 */
int nff_start_task(void);

/**
 * nff_register_command — register a custom command handler.
 *
 * name     — action string matched against the "action" JSON field
 * handler  — callback invoked with the command payload
 * user_ctx — passed back to handler as-is
 *
 * Up to NFF_MAX_USER_CMDS handlers. Returns NFF_ERR_NO_MEM when full.
 * Must be called before nff_connect().
 */
int nff_register_command(const char      *name,
                          nff_cmd_handler_t handler,
                          void             *user_ctx);

/**
 * nff_log — write a formatted log line to the RTC circular buffer and UART.
 *
 * The last NFF_LOG_LINES lines are preserved across software resets and
 * included in crash reports. Use instead of printf/ESP_LOGI in code paths
 * that are useful to diagnose crashes.
 */
void nff_log(const char *fmt, ...);

/**
 * nff_get_state — return the current SDK state.
 */
nff_state_t nff_get_state(void);

/* ------------------------------------------------------------------ */
/* Compile-time limits (override via -D or Kconfig)                    */
/* ------------------------------------------------------------------ */
#ifndef NFF_MAX_USER_CMDS
#  define NFF_MAX_USER_CMDS         8
#endif
#ifndef NFF_TOPIC_MAXLEN
#  define NFF_TOPIC_MAXLEN          128
#endif
#ifndef NFF_RESPONSE_MAXLEN
#  define NFF_RESPONSE_MAXLEN       1024
#endif
#ifndef NFF_MQTT_BUFFER_SIZE
#  define NFF_MQTT_BUFFER_SIZE      1024  /* MQTT RX/TX buffer. OTA cmds are ~400B+ (PubSubClient's 256 default silently drops them). Bump to 2048 for very long pre-signed URLs. */
#endif
#ifndef NFF_HEARTBEAT_INTERVAL_S
#  define NFF_HEARTBEAT_INTERVAL_S  30
#endif
#ifndef NFF_LOG_LINES
#  define NFF_LOG_LINES             32
#endif
#ifndef NFF_LOG_LINE_LEN
#  define NFF_LOG_LINE_LEN          128
#endif
#ifndef NFF_NONCE_RING_SIZE
#  define NFF_NONCE_RING_SIZE       16
#endif
#ifndef NFF_NONCE_LEN
#  define NFF_NONCE_LEN             9    /* 8 hex chars + null terminator */
#endif
#ifndef NFF_TIMESTAMP_WINDOW_S
#  define NFF_TIMESTAMP_WINDOW_S    300  /* ±5 minutes */
#endif

#ifdef __cplusplus
}
#endif

#endif /* NFF_H */
