/**
 * nff.h — nff device SDK public API
 *
 * Single include for device firmware. Pair with credentials.h (generated by
 * `nff provision new-device --id <id>`) which provides the DER-encoded
 * certificate/key byte arrays consumed by NFF_CONFIG / NFF_CONFIG_INITIALIZER.
 *
 * Minimal Arduino usage:
 *
 *   #include <nff.h>
 *   #include "credentials.h"
 *
 *   NFF_CONFIG(cfg, "device-42", "nff.yourdomain.com");
 *
 *   void setup() {
 *       // ... WiFi.begin() / WiFi.waitForConnectResult() ...
 *       nff_init(&cfg);
 *       nff_connect();
 *   }
 *   void loop() {
 *       nff_loop();
 *       // your code
 *   }
 *
 * Command signature format (TBS = to-be-signed):
 *   ping/reboot/diag: "{action}|{nonce}|{timestamp_decimal}"
 *   ota:              "ota|{version}|{sha256hex}|{nonce}|{timestamp_decimal}"
 *   custom:           "{action}|{nonce}|{timestamp_decimal}"
 *   ECDSA-P256 signs SHA-256(TBS). nff server holds the matching private key.
 */

#ifndef NFF_H
#define NFF_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* ------------------------------------------------------------------ */
/* Error codes                                                          */
/* ------------------------------------------------------------------ */
#define NFF_OK                  0
#define NFF_ERR_UNINIT         (-1)
#define NFF_ERR_INVALID_ARG    (-2)
#define NFF_ERR_NO_MEM         (-3)
#define NFF_ERR_MQTT           (-4)
#define NFF_ERR_OTA            (-5)
#define NFF_ERR_SECURITY       (-6)
#define NFF_ERR_NOT_SUPPORTED  (-7)
#define NFF_ERR_TIMEOUT        (-8)
#define NFF_ERR_DOWNGRADE      (-9)
#define NFF_ERR_CHECKSUM       (-10)
#define NFF_ERR_RESUME_UNSUPPORTED (-11)  /* server ignored Range (sent 200 to a resume request) */

/* ------------------------------------------------------------------ */
/* SDK state                                                            */
/* ------------------------------------------------------------------ */
typedef enum {
    NFF_STATE_UNINIT     = 0,
    NFF_STATE_CONNECTING,
    NFF_STATE_CONNECTED,
    NFF_STATE_OTA_ACTIVE,
    NFF_STATE_OTA_TRIAL,   /* a freshly-flashed image is on probation, awaiting the health gate */
    NFF_STATE_ERROR
} nff_state_t;

/* Enrollment mode (DEVICE_OWNERSHIP_DESIGN.md §8). CLAIMED = NVS holds a unique per-device cert;
 * BOOTSTRAP = unclaimed, using the shared firmware-baked batch credential to announce + await
 * rollover. Selected at nff_init by probing NVS. */
typedef enum {
    NFF_MODE_CLAIMED   = 0,
    NFF_MODE_BOOTSTRAP = 1
} nff_mode_t;

/* ------------------------------------------------------------------ */
/* Configuration                                                        */
/* ------------------------------------------------------------------ */
typedef struct {
    const char    *device_id;
    const char    *project_id;         /* tenant scope (NFF_PROJECT_ID); topics namespace under it */
    const char    *broker_host;
    uint16_t       broker_port;        /* default: 8883 (TLS) */

    /* mTLS — DER-encoded byte arrays from credentials.h */
    const uint8_t *client_cert;        size_t client_cert_len;
    const uint8_t *client_key;         size_t client_key_len;
    const uint8_t *ca_cert;            size_t ca_cert_len;

    /* Fleet command verify key: 65-byte uncompressed P-256 point (0x04 || X || Y) */
    const uint8_t *cmd_verify_key;     size_t cmd_verify_key_len;

    /* Firmware identity — injected by build system via -DNFF_FW_VERSION=... */
    const char    *fw_version;
    const char    *build_id;           /* 16-char hex prefix of ELF SHA-256 */
    const char    *fqbn;               /* build target, injected via -DNFF_FQBN=... ("" if unset) */

    /* Tuning */
    uint32_t       heartbeat_interval_s;  /* 0 = use default (30) */

    /* Claim/bootstrap (DEVICE_OWNERSHIP_DESIGN.md §8). Operational configs leave batch_id NULL.
     * intermediate_cert is the project CA presented alongside the leaf so the broker chains to root
     * (NULL when unused). In bootstrap mode, cmd_verify_key holds the fleet ROLLOVER-verify key. */
    const char    *batch_id;                              /* NULL unless bootstrapping */
    const uint8_t *intermediate_cert;  size_t intermediate_cert_len;
} nff_config_t;

/* ------------------------------------------------------------------ */
/* Config convenience macros (require credentials.h in scope)          */
/* ------------------------------------------------------------------ */

/* The build target (fqbn) is injected on the compile command line as a BARE
 * token via -DNFF_FQBN_TOKEN=esp32:esp32:esp32 (see nff flash / the build
 * server). Passing it unquoted avoids cross-shell quoting headaches with the
 * colons; we stringify it here. A direct -DNFF_FQBN="..." still wins, and a
 * bare build with neither flag falls back to "" so the symbol always resolves. */
#ifndef NFF_FQBN
#  ifdef NFF_FQBN_TOKEN
#    define NFF_FQBN_STRINGIFY2(x) #x
#    define NFF_FQBN_STRINGIFY(x)  NFF_FQBN_STRINGIFY2(x)
#    define NFF_FQBN NFF_FQBN_STRINGIFY(NFF_FQBN_TOKEN)
#  else
#    define NFF_FQBN ""
#  endif
#endif

/* NFF_BUILD_ID is injected the same bare-token way (-DNFF_BUILD_ID_TOKEN=abc123): a
 * string passed WITH quotes through arduino-cli's build-property tokenizer loses them
 * (gcc then reports "stray '\'" / "missing terminating \" character"), so the build
 * server passes a bare hex token and we stringify it here. When a token is present it
 * WINS over any earlier NFF_BUILD_ID (e.g. a credentials.h default) so the value baked
 * into the firmware matches what the build server records on the firmware_versions row.
 * With no token, NFF_BUILD_ID keeps coming from credentials.h / a direct -DNFF_BUILD_ID. */
#ifdef NFF_BUILD_ID_TOKEN
#  undef NFF_BUILD_ID
#  define NFF_BUILD_ID_STRINGIFY2(x) #x
#  define NFF_BUILD_ID_STRINGIFY(x)  NFF_BUILD_ID_STRINGIFY2(x)
#  define NFF_BUILD_ID NFF_BUILD_ID_STRINGIFY(NFF_BUILD_ID_TOKEN)
#endif

/* NFF_FW_VERSION is injected the same bare-token way (-DNFF_FW_VERSION_TOKEN=3.0.13):
 * a semver like 3.0.13 is a single valid preprocessing token, but passing it quoted
 * through arduino-cli's build-property tokenizer strips the quotes, so the build server
 * passes it bare and we stringify it here. A token WINS over any earlier NFF_FW_VERSION
 * (e.g. a credentials.h default) so the device reports the release version it was built
 * for and the anti-downgrade gate compares against it. With no token, NFF_FW_VERSION
 * keeps coming from credentials.h / a direct -DNFF_FW_VERSION. */
#ifdef NFF_FW_VERSION_TOKEN
#  undef NFF_FW_VERSION
#  define NFF_FW_VERSION_STRINGIFY2(x) #x
#  define NFF_FW_VERSION_STRINGIFY(x)  NFF_FW_VERSION_STRINGIFY2(x)
#  define NFF_FW_VERSION NFF_FW_VERSION_STRINGIFY(NFF_FW_VERSION_TOKEN)
#endif

/* Arduino / C++ global initializer — positional, C++ compatible */
#define NFF_CONFIG(var, id, host)                               \
    nff_config_t var = {                                        \
        (id),                                                   \
        NFF_PROJECT_ID,                                         \
        (host),                                                 \
        8883,                                                   \
        NFF_CLIENT_CERT_DER,  NFF_CLIENT_CERT_LEN,             \
        NFF_CLIENT_KEY_DER,   NFF_CLIENT_KEY_LEN,              \
        NFF_CA_CERT_DER,      NFF_CA_CERT_LEN,                 \
        NFF_CMD_VERIFY_KEY_DER, NFF_CMD_VERIFY_KEY_LEN,        \
        NFF_FW_VERSION,                                         \
        NFF_BUILD_ID,                                           \
        NFF_FQBN,                                               \
        30,                                                     \
        NULL,                                                   \
        NFF_INTERMEDIATE_CERT_DER, NFF_INTERMEDIATE_CERT_LEN    \
    }

/* ESP-IDF / C99 designated initializer */
#define NFF_CONFIG_INITIALIZER(id, host) {                      \
    .device_id            = (id),                               \
    .project_id           = NFF_PROJECT_ID,                     \
    .broker_host          = (host),                             \
    .broker_port          = 8883,                               \
    .client_cert          = NFF_CLIENT_CERT_DER,                \
    .client_cert_len      = NFF_CLIENT_CERT_LEN,                \
    .client_key           = NFF_CLIENT_KEY_DER,                 \
    .client_key_len       = NFF_CLIENT_KEY_LEN,                 \
    .ca_cert              = NFF_CA_CERT_DER,                    \
    .ca_cert_len          = NFF_CA_CERT_LEN,                    \
    .cmd_verify_key       = NFF_CMD_VERIFY_KEY_DER,             \
    .cmd_verify_key_len   = NFF_CMD_VERIFY_KEY_LEN,             \
    .fw_version           = NFF_FW_VERSION,                     \
    .build_id             = NFF_BUILD_ID,                       \
    .fqbn                 = NFF_FQBN,                           \
    .heartbeat_interval_s = 30,                                 \
    .batch_id             = NULL,                               \
    .intermediate_cert    = NFF_INTERMEDIATE_CERT_DER,          \
    .intermediate_cert_len = NFF_INTERMEDIATE_CERT_LEN,         \
}

/* Bootstrap config: the device boots on the SHARED batch credential and pins the fleet ROLLOVER
 * verify key (not a project key — it has none yet). device_id is left empty; nff_init fills it with
 * the runtime hardware id (nff_port_get_unique_id) since the firmware image is identical across the
 * whole batch. Requires a bootstrap credentials.h (NFF_BATCH_ID, NFF_ROLLOVER_VERIFY_KEY_DER, ...). */
#define NFF_BOOTSTRAP_CONFIG_INITIALIZER(host) {               \
    .device_id            = "",                                 \
    .project_id           = NFF_PROJECT_ID,                     \
    .broker_host          = (host),                             \
    .broker_port          = 8883,                               \
    .client_cert          = NFF_CLIENT_CERT_DER,                \
    .client_cert_len      = NFF_CLIENT_CERT_LEN,                \
    .client_key           = NFF_CLIENT_KEY_DER,                 \
    .client_key_len       = NFF_CLIENT_KEY_LEN,                 \
    .ca_cert              = NFF_CA_CERT_DER,                    \
    .ca_cert_len          = NFF_CA_CERT_LEN,                    \
    .cmd_verify_key       = NFF_ROLLOVER_VERIFY_KEY_DER,        \
    .cmd_verify_key_len   = NFF_ROLLOVER_VERIFY_KEY_LEN,        \
    .fw_version           = NFF_FW_VERSION,                     \
    .build_id             = NFF_BUILD_ID,                       \
    .fqbn                 = NFF_FQBN,                           \
    .heartbeat_interval_s = 30,                                 \
    .batch_id             = NFF_BATCH_ID,                       \
    .intermediate_cert    = NFF_INTERMEDIATE_CERT_DER,          \
    .intermediate_cert_len = NFF_INTERMEDIATE_CERT_LEN,         \
}

/* Zephyr: compile-time thread definition (V1: real port deferred — stub only) */
#define NFF_THREAD_DEFINE(var, id, host)  \
    nff_config_t var = NFF_CONFIG_INITIALIZER((id), (host))

/* ------------------------------------------------------------------ */
/* Command handler                                                      */
/* ------------------------------------------------------------------ */

/**
 * Handler for user-registered commands. Called on the nff task/loop when
 * a signed command arrives. Write JSON to response_buf (null-terminated);
 * the SDK publishes it to nff/devices/{id}/response.
 *
 * payload      — null-terminated JSON string of the full command
 * response_buf — write your JSON reply here; max response_len bytes
 * user_ctx     — opaque pointer passed to nff_register_command
 */
typedef void (*nff_cmd_handler_t)(const char  *payload,
                                   char        *response_buf,
                                   size_t       response_len,
                                   void        *user_ctx);

/**
 * Optional health-check callback for OTA rollback. After an OTA the new image
 * runs on probation; the SDK commits it (cancels rollback) once MQTT reconnects
 * AND this callback — if registered — returns true. Returning false, or never
 * returning true before NFF_OTA_CONFIRM_TIMEOUT_S elapses, makes the device
 * automatically revert to the previous image and report "rolled_back".
 *
 * Called repeatedly on the nff loop/task while on probation. Must be
 * non-blocking. user_ctx is the value passed to nff_register_health_check.
 */
typedef bool (*nff_health_check_t)(void *user_ctx);

/* ------------------------------------------------------------------ */
/* Public API                                                           */
/* ------------------------------------------------------------------ */

/**
 * nff_init — initialise the SDK.
 *
 * Call once before WiFi connect. Installs the panic hook, detects a
 * crash on the previous boot, and checks for a pending OTA result.
 * Safe to call from app_main (ESP-IDF) or global constructors (Arduino).
 */
int nff_init(const nff_config_t *cfg);

/**
 * nff_connect — connect to the nff broker.
 *
 * Call after WiFi is up. Performs the mTLS handshake, publishes the
 * retained heartbeat, and subscribes to the command topic.
 * Returns NFF_OK on success. On failure the SDK will retry automatically
 * via nff_loop() / the internal FreeRTOS task.
 */
int nff_connect(void);

/**
 * nff_loop — non-blocking poll for Arduino sketch loop().
 *
 * Drives MQTT keepalive, reconnect backoff, and heartbeat timer.
 * Returns in < 1 ms when there is no pending work.
 */
void nff_loop(void);

/**
 * nff_start_task — create a FreeRTOS task for nff (ESP-IDF / Arduino-FreeRTOS).
 *
 * Pins the task to Core 0, runs at priority 2 (lower than any application task).
 * Returns immediately. The application continues on Core 1.
 * Do NOT call nff_loop() when using nff_start_task().
 */
int nff_start_task(void);

/**
 * nff_register_command — register a custom command handler.
 *
 * name     — action string matched against the "action" JSON field
 * handler  — callback invoked with the command payload
 * user_ctx — passed back to handler as-is
 *
 * Up to NFF_MAX_USER_CMDS handlers. Returns NFF_ERR_NO_MEM when full.
 * Must be called before nff_connect().
 */
int nff_register_command(const char      *name,
                          nff_cmd_handler_t handler,
                          void             *user_ctx);

/**
 * nff_register_health_check — register an optional OTA self-test callback.
 *
 * Used by the automatic OTA rollback gate (see nff_health_check_t). Pass NULL
 * cb to clear. When unset, the gate uses broker reconnect alone. Returns NFF_OK.
 * Must be called before nff_connect().
 */
int nff_register_health_check(nff_health_check_t cb, void *user_ctx);

/**
 * nff_log — write a formatted log line to the RTC circular buffer and UART.
 *
 * The last NFF_LOG_LINES lines are preserved across software resets and
 * included in crash reports. Use instead of printf/ESP_LOGI in code paths
 * that are useful to diagnose crashes.
 */
void nff_log(const char *fmt, ...);

/**
 * nff_get_state — return the current SDK state.
 */
nff_state_t nff_get_state(void);

#if NFF_BOOTSTRAP_ENABLED
/**
 * nff_get_mode — CLAIMED (NVS has a per-device cert) or BOOTSTRAP (unclaimed). Valid after nff_init.
 */
nff_mode_t nff_get_mode(void);

/**
 * nff_bootstrap_run — connect on the shared batch credential, announce this device for enrollment,
 * and idle until the fleet rolls over a per-device cert (then the device reboots into CLAIMED mode).
 * Only meaningful when nff_get_mode() == NFF_MODE_BOOTSTRAP.
 */
int nff_bootstrap_run(void);
#endif

/* ------------------------------------------------------------------ */
/* Compile-time limits (override via -D or Kconfig)                    */
/* ------------------------------------------------------------------ */
#ifndef NFF_MAX_USER_CMDS
#  define NFF_MAX_USER_CMDS         8
#endif
#ifndef NFF_TOPIC_MAXLEN
/* Fits nff/{project_id}/devices/{device_id}/{type} — project_id is a UUID (36 chars). */
#  define NFF_TOPIC_MAXLEN          192
#endif
#ifndef NFF_RESPONSE_MAXLEN
#  define NFF_RESPONSE_MAXLEN       1024
#endif
/* Claim enrollment: gate every bootstrap/rollover/NVS code path. Default off so existing
 * operational-only builds are byte-for-byte unchanged. Build a bootstrap image with -DNFF_BOOTSTRAP_ENABLED=1. */
#ifndef NFF_BOOTSTRAP_ENABLED
#  define NFF_BOOTSTRAP_ENABLED     0
#endif
/* Rollover commands carry several DER blobs (base64) and run ~4-6 KB, so a bootstrap build needs a
 * much larger MQTT RX buffer than the 1 KB operational default (PubSubClient/esp-mqtt silently drop
 * or truncate oversize PUBLISHes — see NFF_MQTT_BUFFER_SIZE note). */
#ifndef NFF_ROLLOVER_MQTT_BUFFER_SIZE
#  define NFF_ROLLOVER_MQTT_BUFFER_SIZE  8192
#endif
#ifndef NFF_MQTT_BUFFER_SIZE
#  if NFF_BOOTSTRAP_ENABLED
#    define NFF_MQTT_BUFFER_SIZE    NFF_ROLLOVER_MQTT_BUFFER_SIZE
#  else
#    define NFF_MQTT_BUFFER_SIZE    1024  /* MQTT RX/TX buffer. OTA cmds are ~400B+ (PubSubClient's 256 default silently drops them). Bump to 2048 for very long pre-signed URLs. */
#  endif
#endif
#ifndef NFF_CMD_MAXLEN
#  define NFF_CMD_MAXLEN            NFF_MQTT_BUFFER_SIZE  /* inbound command parse buffer (nff_cmd_dispatch). Must hold the largest signed command (e.g. an OTA cmd carrying a pre-signed URL); keep >= NFF_MQTT_BUFFER_SIZE so the MQTT layer never delivers more than the parser can hold. */
#endif
#ifndef NFF_HEARTBEAT_INTERVAL_S
#  define NFF_HEARTBEAT_INTERVAL_S  30
#endif
#ifndef NFF_LOG_LINES
#  define NFF_LOG_LINES             32
#endif
#ifndef NFF_LOG_LINE_LEN
#  define NFF_LOG_LINE_LEN          128
#endif
#ifndef NFF_NONCE_RING_SIZE
#  define NFF_NONCE_RING_SIZE       16
#endif
#ifndef NFF_NONCE_LEN
#  define NFF_NONCE_LEN             9    /* 8 hex chars + null terminator */
#endif
#ifndef NFF_TIMESTAMP_WINDOW_S
#  define NFF_TIMESTAMP_WINDOW_S    300  /* ±5 minutes */
#endif
/* Automatic OTA rollback (IOT_BRIDGE.md §3). A freshly-flashed image runs on
 * probation; it is committed only once it reconnects to the broker (and any
 * registered health-check passes) within the confirm window, else the device
 * reverts to the previous image. */
#ifndef NFF_OTA_CONFIRM_TIMEOUT_S
#  define NFF_OTA_CONFIRM_TIMEOUT_S 60   /* time to prove healthy before rollback */
#endif
#ifndef NFF_OTA_MAX_TRIAL_BOOTS
#  define NFF_OTA_MAX_TRIAL_BOOTS   3    /* unconfirmed boots tolerated before rollback (crash-loop guard) */
#endif
/* Resumable OTA download (IOT_BRIDGE.md §3 gap #6). A transient TLS stall mid-download is
 * retried with an HTTP Range header from where it stopped (SHA-256 context kept in RAM), so a
 * dropped transfer on flaky cellular does not restart from byte 0. In-session only — not
 * persisted across reboots. */
#ifndef NFF_OTA_MAX_DL_RETRIES
#  define NFF_OTA_MAX_DL_RETRIES    4    /* download attempts before giving up the OTA */
#endif
#ifndef NFF_OTA_DL_RETRY_BACKOFF_MS
#  define NFF_OTA_DL_RETRY_BACKOFF_MS 2000  /* delay between resume attempts */
#endif
/* Deeper default OTA health gate (IOT_BRIDGE.md §3 gap #7). Beyond "broker reconnects", the SDK
 * requires a minimum free-heap floor AND that the new image stays healthy for a soak window
 * before committing. Both are AND'd with any nff_register_health_check() callback. */
#ifndef NFF_OTA_MIN_HEAP_FLOOR
#  define NFF_OTA_MIN_HEAP_FLOOR    20000  /* bytes; min_free_heap must stay above this to commit */
#endif
#ifndef NFF_OTA_MIN_HEALTHY_MS
#  define NFF_OTA_MIN_HEALTHY_MS    5000   /* image must hold healthy this long before commit (soak) */
#endif

#ifdef __cplusplus
}
#endif

#endif /* NFF_H */
